@startuml Vocabulario

Conecta4 *-down-> "2" Player
Conecta4 *-down-> Board
Conecta4 *-down-> Turn

Turn -down-> "2" Player

Player -down-> Board
Player o-down-> "0..4" Piece
Player o-down-> Goal
Player *-down-> Color


Action <|-down- Put
Action <|-down- Move

Piece *-down-> Color

Color <|-down- X
Color <|-down- O

Goal ..> "4" Put
Goal ..> "*" Move
Goal ..> "4" Square

Board *-down-> "nxn" Square
Square *-down-> Coordinate
Square o-down-> "0..1" Piece

Action .down.> Piece
Action .down.> Square : target
Move .down.> Square : origin

Goal <|-down- Row
Goal <|-down- Column
Goal <|-down- Diagonal

@enduml

@startuml Instrucciones

state A as " "
state B as " "
state C as " "
state D as " "
state E as " "
[*] --> A
A --> B: put X
B --> A : put O
B --> C : [isFull]
C --> D : put O
C --> [*] : [hasWonX]
D --> [*] : [hasWonO]
C --> [*] : [finish]

@enduml
